---
- name: Install Zabbix repository
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/6.4/debian/ buster main"
    state: present
    filename: zabbix

- name: Add MySQL apt key
  apt_key:
    url: https://repo.mysql.com/RPM-GPG-KEY-mysql
    state: present
- name: Add MySQL repository
  apt_repository:
    repo: 'deb https://repo.mysql.com/apt/debian/dists/bullseye/'
    state: present
    update_cache: yes
    # cache_valid_time: 3600
    filename: 'mysql'

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Zabbix packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-server
    - zabbix-server-mysql
    - zabbix-frontend-php
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-agent
    - python3-pymysql

- name: Create initial database
  mysql_db:
    name: zabbix
    state: present
    collation: utf8mb4_bin

- name: Create database user
  mysql_user:
    name: zabbix
    password: "{{ zabbix_db_password }}"
    priv: 'zabbix.*:ALL'
    host: localhost

- name: Enable log_bin_trust_function_creators
  mysql_variables:
    name: log_bin_trust_function_creators
    value: 1
    login_user: root
    login_password: "{{ zabbix_db_password }}"

- name: Import initial schema and data
  command: "zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p{{ zabbix_db_password }} zabbix"
  args:
    creates: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  become: yes

- name: Disable log_bin_trust_function_creators
  mysql_variables:
    name: log_bin_trust_function_creators
    value: 0
    login_user: root
    login_password: "{{ zabbix_db_password }}"

- name: Configure Zabbix server database password
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^DBPassword='
    line: 'DBPassword={{ zabbix_db_password }}'

- name: Configure PHP for Zabbix frontend
  lineinfile:
    path: /etc/zabbix/nginx.conf
    regexp: '^# (listen|server_name)'
    line: '{{ item }}'
  loop:
    - 'listen 8080;'
    - 'server_name example.com;'

- name: Restart Zabbix server, agent, and nginx
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent
    - nginx
    - php7.4-fpm